name: imransiddiqui
favicon: null
layout_spectrum: 0.9236042387783527
typography_spectrum: 0.5596987640019506
title: To Each Soul What She Strives For
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6875
  lightness: 0.9128886167891324
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
