name: imransiddiqui
favicon: null
layout_spectrum: 0.24372
typography_spectrum: 0.83587
title: To Each Soul What She Strives For
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e7d8af'
    - '#dec195'
    - '#814344'
    - '#bc7475'
    - '#44232a'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
